### ISSUE TITLE
ModuleNotFoundError: No module named 'bs4' on -gdl

### ISSUE THREAD

**Issue by paradonym** [igbt6/Packt-Publishing-Free-Learning#116]
Followed README.md setup until usage part:
it's all in a subdir with python 3.7.1 embeddable zip included... Should I always use an installed zip instead of an embedded one?

Full installation:

```powershell
Windows PowerShell
Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.

PS C:\packt> .\python.exe .\get-pip.py
Collecting pip
  Downloading https://files.pythonhosted.org/packages/c2/d7/90f34cb0d83a6c5631cf71dfe64cc1054598c843a92b400e55675cc2ac37/pip-18.1-py2.py3-none-any.whl (1.3MB)
    100% |████████████████████████████████| 1.3MB 3.1MB/s
Collecting setuptools
  Downloading https://files.pythonhosted.org/packages/e7/16/da8cb8046149d50940c6110310983abb359bbb8cbc3539e6bef95c29428a/setuptools-40.6.2-py2.py3-none-any.whl (573kB)
    100% |████████████████████████████████| 573kB 3.9MB/s
Collecting wheel
  Downloading https://files.pythonhosted.org/packages/ff/47/1dfa4795e24fd6f93d5d58602dd716c3f101cfd5a77cd9acbe519b44a0a9/wheel-0.32.3-py2.py3-none-any.whl
Installing collected packages: pip, setuptools, wheel
  The script wheel.exe is installed in 'C:\packt\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed pip-18.1 setuptools-40.6.2 wheel-0.32.3
PS C:\packt> pip install virtualenv
Collecting virtualenv
  Downloading https://files.pythonhosted.org/packages/7c/17/9b7b6cddfd255388b58c61e25b091047f6814183e1d63741c8df8dcd65a2/virtualenv-16.1.0-py2.py3-none-any.whl (1.9MB)
    100% |████████████████████████████████| 1.9MB 4.1MB/s
Installing collected packages: virtualenv
  The script virtualenv.exe is installed in 'c:\python37\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed virtualenv-16.1.0
You are using pip version 10.0.1, however version 18.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
PS C:\packt> pip install -r .\requirements.txt
Collecting requests==2.18.4 (from -r .\requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/49/df/50aa1999ab9bde74656c2919d9c0c085fd2b3775fd3eca826012bef76d8c/requests-2.18.4-py2.py3-none-any.whl (88kB)
    100% |████████████████████████████████| 92kB 1.8MB/s
Collecting beautifulsoup4==4.6.0 (from -r .\requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/9e/d4/10f46e5cfac773e22707237bfcd51bbffeaf0a576b0a847ec7ab15bd7ace/beautifulsoup4-4.6.0-py3-none-any.whl (86kB)
    100% |████████████████████████████████| 92kB 4.0MB/s
Collecting configparser==3.5.0 (from -r .\requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/7c/69/c2ce7e91c89dc073eb1aa74c0621c3eefbffe8216b3f9af9d3885265c01c/configparser-3.5.0.tar.gz
Collecting future==0.16.0 (from -r .\requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/00/2b/8d082ddfed935f3608cc61140df6dcbf0edea1bc3ab52fb6c29ae3e81e85/future-0.16.0.tar.gz (824kB)
    100% |████████████████████████████████| 829kB 3.2MB/s
Collecting google-api-python-client==1.6.3 (from -r .\requirements.txt (line 5))
  Downloading https://files.pythonhosted.org/packages/cd/f1/189844cdec37df2b392d8367f1df23da697f1526d7eaf91ee7c3e83ce092/google_api_python_client-1.6.3-py2.py3-none-any.whl (53kB)
    100% |████████████████████████████████| 61kB 2.9MB/s
Collecting mccabe==0.6.1 (from -r .\requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/87/89/479dc97e18549e21354893e4ee4ef36db1d237534982482c3681ee6e7b57/mccabe-0.6.1-py2.py3-none-any.whl
Collecting pycodestyle==2.3.1 (from -r .\requirements.txt (line 7))
  Downloading https://files.pythonhosted.org/packages/e4/81/78fe51eb4038d1388b7217dd63770b0f428370207125047312886c923b26/pycodestyle-2.3.1-py2.py3-none-any.whl (45kB)
    100% |████████████████████████████████| 51kB 2.8MB/s
Collecting pyflakes==1.6.0 (from -r .\requirements.txt (line 8))
  Downloading https://files.pythonhosted.org/packages/d7/40/733bcc64da3161ae4122c11e88269f276358ca29335468005cb0ee538665/pyflakes-1.6.0-py2.py3-none-any.whl (227kB)
    100% |████████████████████████████████| 235kB 4.7MB/s
Collecting pylama==7.4.1 (from -r .\requirements.txt (line 9))
  Downloading https://files.pythonhosted.org/packages/86/7c/af2d7d1d93cb588393e41ea43365224d9336b936bef96b353fff564ea48f/pylama-7.4.1-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests==2.18.4->-r .\requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/56/9d/1d02dd80bc4cd955f98980f28c5ee2200e1209292d5f9e9cc8d030d18655/certifi-2018.10.15-py2.py3-none-any.whl (146kB)
    100% |████████████████████████████████| 153kB 4.9MB/s
Collecting chardet<3.1.0,>=3.0.2 (from requests==2.18.4->-r .\requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)
    100% |████████████████████████████████| 143kB 4.5MB/s
Collecting idna<2.7,>=2.5 (from requests==2.18.4->-r .\requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/27/cc/6dd9a3869f15c2edfab863b992838277279ce92663d334df9ecf5106f5c6/idna-2.6-py2.py3-none-any.whl (56kB)
    100% |████████████████████████████████| 61kB 2.9MB/s
Collecting urllib3<1.23,>=1.21.1 (from requests==2.18.4->-r .\requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/63/cb/6965947c13a94236f6d4b8223e21beb4d576dc72e8130bd7880f600839b8/urllib3-1.22-py2.py3-none-any.whl (132kB)
    100% |████████████████████████████████| 133kB 4.7MB/s
Collecting six<2dev,>=1.6.1 (from google-api-python-client==1.6.3->-r .\requirements.txt (line 5))
  Downloading https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Collecting httplib2<1dev,>=0.9.2 (from google-api-python-client==1.6.3->-r .\requirements.txt (line 5))
  Downloading https://files.pythonhosted.org/packages/ce/ed/803905d670b52fa0edfdd135337e545b4496c2ab3a222f1449b7256eb99f/httplib2-0.12.0.tar.gz (218kB)
    100% |████████████████████████████████| 225kB 3.4MB/s
Collecting oauth2client<5.0.0dev,>=1.5.0 (from google-api-python-client==1.6.3->-r .\requirements.txt (line 5))
  Downloading https://files.pythonhosted.org/packages/95/a9/4f25a14d23f0786b64875b91784607c2277eff25d48f915e39ff0cff505a/oauth2client-4.1.3-py2.py3-none-any.whl (98kB)
    100% |████████████████████████████████| 102kB 4.1MB/s
Collecting uritemplate<4dev,>=3.0.0 (from google-api-python-client==1.6.3->-r .\requirements.txt (line 5))
  Downloading https://files.pythonhosted.org/packages/e5/7d/9d5a640c4f8bf2c8b1afc015e9a9d8de32e13c9016dcc4b0ec03481fb396/uritemplate-3.0.0-py2.py3-none-any.whl
Collecting pydocstyle>=2.0.0 (from pylama==7.4.1->-r .\requirements.txt (line 9))
  Downloading https://files.pythonhosted.org/packages/6e/3f/9207e1af3fb23c71a2a17a5d82d4c68f4dd6b3429b58514c74b95f6e0784/pydocstyle-3.0.0-py3-none-any.whl
Collecting rsa>=3.1.4 (from oauth2client<5.0.0dev,>=1.5.0->google-api-python-client==1.6.3->-r .\requirements.txt (line 5))
  Downloading https://files.pythonhosted.org/packages/02/e5/38518af393f7c214357079ce67a317307936896e961e35450b70fad2a9cf/rsa-4.0-py2.py3-none-any.whl
Collecting pyasn1-modules>=0.0.5 (from oauth2client<5.0.0dev,>=1.5.0->google-api-python-client==1.6.3->-r .\requirements.txt (line 5))
  Downloading https://files.pythonhosted.org/packages/19/02/fa63f7ba30a0d7b925ca29d034510fc1ffde53264b71b4155022ddf3ab5d/pyasn1_modules-0.2.2-py2.py3-none-any.whl (62kB)
    100% |████████████████████████████████| 71kB 3.1MB/s
Collecting pyasn1>=0.1.7 (from oauth2client<5.0.0dev,>=1.5.0->google-api-python-client==1.6.3->-r .\requirements.txt (line 5))
  Downloading https://files.pythonhosted.org/packages/d1/a1/7790cc85db38daa874f6a2e6308131b9953feb1367f2ae2d1123bb93a9f5/pyasn1-0.4.4-py2.py3-none-any.whl (72kB)
    100% |████████████████████████████████| 81kB 3.4MB/s
Collecting snowballstemmer (from pydocstyle>=2.0.0->pylama==7.4.1->-r .\requirements.txt (line 9))
  Downloading https://files.pythonhosted.org/packages/d4/6c/8a935e2c7b54a37714656d753e4187ee0631988184ed50c0cf6476858566/snowballstemmer-1.2.1-py2.py3-none-any.whl (64kB)
    100% |████████████████████████████████| 71kB 3.3MB/s
Installing collected packages: certifi, chardet, idna, urllib3, requests, beautifulsoup4, configparser, future, six, httplib2, pyasn1, rsa, pyasn1-modules, oauth2client, uritemplate, google-api-python-client, mccabe, pycodestyle, pyflakes, snowballstemmer, pydocstyle, pylama
  The script chardetect.exe is installed in 'c:\python37\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Running setup.py install for configparser ... done
  Running setup.py install for future ... done
  Running setup.py install for httplib2 ... done
  The scripts pyrsa-decrypt.exe, pyrsa-encrypt.exe, pyrsa-keygen.exe, pyrsa-priv2pub.exe, pyrsa-sign.exe and pyrsa-verify.exe are installed in 'c:\python37\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  The script pycodestyle.exe is installed in 'c:\python37\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  The script pyflakes.exe is installed in 'c:\python37\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  The script pydocstyle.exe is installed in 'c:\python37\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  The script pylama.exe is installed in 'c:\python37\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed beautifulsoup4-4.6.0 certifi-2018.10.15 chardet-3.0.4 configparser-3.5.0 future-0.16.0 google-api-python-client-1.6.3 httplib2-0.12.0 idna-2.6 mccabe-0.6.1 oauth2client-4.1.3 pyasn1-0.4.4 pyasn1-modules-0.2.2 pycodestyle-2.3.1 pydocstyle-3.0.0 pyflakes-1.6.0 pylama-7.4.1 requests-2.18.4 rsa-4.0 six-1.11.0 snowballstemmer-1.2.1 uritemplate-3.0.0 urllib3-1.22
You are using pip version 10.0.1, however version 18.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
PS C:\packt> .\python.exe .\packtPublishingFreeEbook.py -gdl
Traceback (most recent call last):
  File ".\packtPublishingFreeEbook.py", line 15, in <module>
    from bs4 import BeautifulSoup
ModuleNotFoundError: No module named 'bs4'
PS C:\packt> pip install bs4
Collecting bs4
  Downloading https://files.pythonhosted.org/packages/10/ed/7e8b97591f6f456174139ec089c769f89a94a1a4025fe967691de971f314/bs4-0.0.1.tar.gz
Requirement already satisfied: beautifulsoup4 in c:\python37\lib\site-packages (from bs4) (4.6.0)
Installing collected packages: bs4
  Running setup.py install for bs4 ... done
Successfully installed bs4-0.0.1
You are using pip version 10.0.1, however version 18.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
PS C:\packt> .\python.exe .\packtPublishingFreeEbook.py -gdl
Traceback (most recent call last):
  File ".\packtPublishingFreeEbook.py", line 15, in <module>
    from bs4 import BeautifulSoup
ModuleNotFoundError: No module named 'bs4'
```

**Comment by mjenczmyk** [comment]
I can see several issues here. I may be more or less right here as I don't use Windows regularly and certainly not for development. 

1) You are installing `virtualenv`, but you don't create any virtualenv to install packages to (but that isn't a reason of this errors).
2) Could you run `Get-Command pip` and post the output here?
3) There will be some issues with Python 3.7 until https://github.com/igbt6/Packt-Publishing-Free-Learning/pull/114 or https://github.com/igbt6/Packt-Publishing-Free-Learning/pull/111 will be merged (pylama and her companions will complain on install).

Anyway, why don't you install Windows x86 executable installer from https://www.python.org/downloads/release/python-371/ instead of using zipped version?

**Comment by paradonym** [comment]
```powershell
PS C:\packt> .\python.exe --version
Python 3.6.7
PS C:\packt> Get-Command pip

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     pip.exe                                            0.0.0.0    C:\Python37\Scripts\pip.exe


PS C:\packt> .\python.exe .\packtPublishingFreeEbook.py -gdl
Traceback (most recent call last):
  File ".\packtPublishingFreeEbook.py", line 15, in <module>
    from bs4 import BeautifulSoup
ModuleNotFoundError: No module named 'bs4'
PS C:\packt> pip install BeautifulSoup4
Requirement already satisfied: BeautifulSoup4 in c:\python37\lib\site-packages (4.6.0)
You are using pip version 10.0.1, however version 18.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
PS C:\packt>
```

It seems that bs4 is dependend on the Python version and there seem to be different pip packages for python2 and 3 https://stackoverflow.com/questions/11783875/importerror-no-module-named-bs4-beautifulsoup...
```powershell
PS C:\packt> easy_install beautifulsoup4
Searching for beautifulsoup4
Best match: beautifulsoup4 4.6.0
Adding beautifulsoup4 4.6.0 to easy-install.pth file

Using c:\python37\lib\site-packages
Processing dependencies for beautifulsoup4
Finished processing dependencies for beautifulsoup4
PS C:\packt> pip install beautifulsoup4
Requirement already satisfied: beautifulsoup4 in c:\python37\lib\site-packages (4.6.0)
You are using pip version 10.0.1, however version 18.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
PS C:\packt>
```
but it seems that the python3 version of bs4 is installed.
I'll try to downgrade installed python to 3.6.x It seems that a reboot is necessary for this, so I'll try to stick to the embeddable pythons (which are integrateable into projects which sometimes then are movable even between systems)

**Comment by mjenczmyk** [comment]
I'm using the script with Python 3.5, I've also checked that it works for me with Python 3.7 on Debian (installed from source). I suppose you are installing dependencies via `pip` into different Python installation than you run the script.

Your `pip` seems to be installed in `C:\Python37` (which suggests installing packages for Python 3.7), but the Python version you run the script with seems to be 3.6.7. What does `Get-Command python` or `Get-Command python.exe` returns run in your home directory?
