### ISSUE TITLE
Some unicode crap in book title generates error

### ISSUE THREAD

**Issue by tgagor** [igbt6/Packt-Publishing-Free-Learning#29]
Hi again,

thanks god they enabled free ebooks again! :)

Today's one `Kali Linux – Assuring Security by Penetration Testing` have strange unicode dash that generates error:
```
[INFO] - Creating session...
[INFO] - Session created, logged in successfully!
[INFO] - Start grabbing eBook...
[INFO] - Getting data of all your books...
[INFO] - Opened 'https://www.packtpub.com/account/my-ebooks' successfully!
[INFO] - Title: 'Kali Linux   Assuring Security by Penetration Testing'
[INFO] - Downloading eBook: 'Kali Linux   Assuring Security by Penetration Testing' in .pdf format...
[PROGRESS] - [################################################# ] 100.0% [SUCCESS] - eBook: 'Kali Linux   Assuring Security by Penetration Testing.pdf' downloaded successfully!
[INFO] - Title: 'Kali Linux   Assuring Security by Penetration Testing'
[INFO] - Downloading eBook: 'Kali Linux   Assuring Security by Penetration Testing' in .mobi format...
[PROGRESS] - [################################################# ] 100.0% [SUCCESS] - eBook: 'Kali Linux   Assuring Security by Penetration Testing.mobi' downloaded successfully!
[INFO] - 2 eBooks have been downloaded!
[SUCCESS] - Good, looks like all went well! :-)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.4/logging/__init__.py", line 980, in emit
    stream.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2013' in position 68: ordinal not in range(128)
Call stack:
  File "/opt/ppfl/packtPublishingFreeEbook.py", line 331, in <module>
    grabber.grabEbook()
  File "/opt/ppfl/packtPublishingFreeEbook.py", line 176, in grabEbook
    logger.success("eBook: '{}' has been successfully grabbed!".format(self.bookTitle))
  File "/opt/ppfl/utils/logger.py", line 16, in <lambda>
    logger.success = lambda msg, *args: logger._log(logging.SUCCESS, msg, args)
Message: "eBook: 'Kali Linux \u2013 Assuring Security by Penetration Testing' has been successfully grabbed!"
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.4/logging/__init__.py", line 980, in emit
    stream.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2013' in position 31: ordinal not in range(128)
Call stack:
  File "/opt/ppfl/packtPublishingFreeEbook.py", line 331, in <module>
    grabber.grabEbook()
  File "/opt/ppfl/packtPublishingFreeEbook.py", line 176, in grabEbook
    logger.success("eBook: '{}' has been successfully grabbed!".format(self.bookTitle))
  File "/opt/ppfl/utils/logger.py", line 16, in <lambda>
    logger.success = lambda msg, *args: logger._log(logging.SUCCESS, msg, args)
Message: "eBook: 'Kali Linux \u2013 Assuring Security by Penetration Testing' has been successfully grabbed!"
Arguments: ()
```

If this happens once, it will happen again in future.

Ebook was grabbed and downloaded successfully but with filename without unicode sign:
```
Kali Linux   Assuring Security by Penetration Testing.mobi
```

**Comment by josevill** [comment]
I got that error too, then i ran the script once again and got it working successfully, although it didn't get the dash, it wouldn't show any errors again, we might need to adapt the script to handle unicodes in the book's name.

**Comment by tgagor** [comment]
I didn't test script in Python 3
Should it be working?

**Comment by igbt6** [comment]
problems with unicodes already fixed on master, check this out!
