### ISSUE TITLE
Error at exit

### ISSUE THREAD

**Issue by tomipnh** [igbt6/Packt-Publishing-Free-Learning#39]
After grab and download book program doesn't exit clean.

[INFO] - Creating session...
[INFO] - Session created, logged in successfully!
[INFO] - Start grabbing eBook...
[SUCCESS] - eBook: 'OpenCV_for_Secret_Agents' has been successfully grabbed!
[INFO] - Getting data of all your books...
[INFO] - Opened 'https://www.packtpub.com/account/my-ebooks' successfully!
[INFO] - Title: 'OpenCV_for_Secret_Agents'
[INFO] - Downloading eBook: 'OpenCV_for_Secret_Agents' in .pdf format...
[SUCCESS] - eBook: 'OpenCV_for_Secret_Agents.pdf' downloaded successfully!
[INFO] - Title: 'OpenCV_for_Secret_Agents'
[INFO] - Downloading eBook: 'OpenCV_for_Secret_Agents' in .epub format...
[SUCCESS] - eBook: 'OpenCV_for_Secret_Agents.epub' downloaded successfully!
[INFO] - Title: 'OpenCV_for_Secret_Agents'
[INFO] - Downloading code for eBook: 'OpenCV_for_Secret_Agents'...
Traceback (most recent call last):
  File "packtPublishingFreeEbook.py", line 345, in <module>
    downloader.downloadBooks([grabber.bookTitle], intoFolder = intoFolder)
  File "packtPublishingFreeEbook.py", line 275, in downloadBooks
    for num, chunk in enumerate(r.iter_content(chunk_size=1024)):
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 719, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/response.py", line 432, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/response.py", line 380, in read
    data = self._fp.read(amt)
  File "/usr/lib/python2.7/httplib.py", line 573, in read
    s = self.fp.read(amt)
  File "/usr/lib/python2.7/socket.py", line 380, in read
    data = self._sock.recv(left)
KeyboardInterrupt

**Comment by igbt6** [comment]
hmm, seems you stopped the script fro Keyboard manually so where is the actual problem ?

**Comment by tomipnh** [comment]
i did after about 20 minutes waiting

**Comment by mjenczmyk** [comment]
One could catch `ctrl+C` to exit from script gracefully.
