### ISSUE TITLE
Email notifications should allow sending email without login/password and/or TLS

### ISSUE THREAD

**Issue by eharris** [igbt6/Packt-Publishing-Free-Learning#53]
When trying to send an email using localhost or another "internal" mail server, it fails:

```
Traceback (most recent call last):
  File "src/packtPublishingFreeEbook.py", line 408, in <module>
    mb = MailBook(cfg_file_path)
  File "<removed>/prg/Packt-Publishing-Free-Learning/src/utils/mail.py", line 29, in __init__
    self._email_pass = config.get("MAIL", 'password')
  File "/usr/lib/python2.7/ConfigParser.py", line 618, in get
    raise NoOptionError(option, section)
ConfigCarser.NoOptionError: No option 'password' in section: 'MAIL'
```

(Note that I've hacked the script to use ConfigParser since I have an older version of Python installed)

Also, the email fails if the given server doesn't support TLS (which isn't needed if the server is local/private):

```
[ERROR] - Sending failed with an error: STARTTLS extension not supported by server.
```

**Comment by igbt6** [comment]
@eharris Feel free to open some PR  : )

**Comment by igbt6** [comment]
Closed for now, no need for such update
